# Queues a deploy command for every local PR.

name: Local PR Opened/Updated

on:
  pull_request:

jobs:
  dispatch-deploy-command:
    if: github.repository == github.event.pull_request.head.repo.full_name
    runs-on: ubuntu-latest
    steps:
    - name: Dispatch /deploy Command
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.DISPATCH_TOKEN }}
        event-type: deploy-command
        client-payload: '{"pull_request": ${{ toJson(github.event.pull_request) }}}'
